package symposium.model;

/**
 * This class is an enum class which holds the values for Priorities.
 * An enum type is a special data type that enables for a variable to be a set of predefined constants.
 * This class is used to describe the Priorities for the constaints, which are fixed.
 * The order matters for these enums since we use autoGenerated compareTo() and it compares them by natural order
 * This means that smaller is first and greater is last
 */

public enum ConstraintPriority {
    DESIRED , VERY_IMPORTANT, REQUIRED
}
