package symposium.model;

public enum ConstraintPriority {
    // The order matters : we use autoGenerated compareTo() and it compares them by natural order
    // This means that smaller is first and greater is last
    DESIRED , VERY_IMPORTANT, REQUIRED
}
