package symposium.model;

/**
 * This class is an enum class which hold the values for Priorities.
 * An enum type is a special data type that enables for a variable to be a set of predefined constants.
 * This class is implemented since the Priorities are fixed set of constants for the schedule.
 * The order matters for these enums matters since when we use autoGenerated compareTo() and it compares them by natural order
 * This means that smaller is first and greater is last
 */

public enum ConstraintPriority {
    DESIRED , VERY_IMPORTANT, REQUIRED
}
