package symposium.gui;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import symposium.Report;

public class ResultWin extends javax.swing.JDialog {

    /**
     * Creates new form ResultFrame
     */
    public ResultWin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        outputJsonFileChooser.setFileFilter(new FileNameExtensionFilter("Schedule Json (json)", "json"));
        outputTextFileChooser.setFileFilter(new FileNameExtensionFilter("Schedule Text (txt)", "txt"));
    }
    
    public void showSchedule() {
        this.resultTxt.setText(Report.INSTANCE.toString());
        this.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputJsonFileChooser = new javax.swing.JFileChooser();
        outputTextFileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTxt = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        saveJsonBtn = new javax.swing.JButton();
        saveTextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        resultTxt.setEditable(false);
        resultTxt.setColumns(20);
        resultTxt.setRows(5);
        jScrollPane1.setViewportView(resultTxt);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveJsonBtn.setText("Save Json...");
        saveJsonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJsonBtnActionPerformed(evt);
            }
        });

        saveTextBtn.setText("Save Text...");
        saveTextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(saveTextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveJsonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveJsonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveTextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveJsonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJsonBtnActionPerformed
        if(this.outputJsonFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            MainWin.saveFile(this,this.outputJsonFileChooser.getSelectedFile(), Report.INSTANCE.toJson().toString());
        }
    }//GEN-LAST:event_saveJsonBtnActionPerformed

    private void saveTextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTextBtnActionPerformed
        if(this.outputTextFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            MainWin.saveFile(this, this.outputTextFileChooser.getSelectedFile(), Report.INSTANCE.toString());
        }
    }//GEN-LAST:event_saveTextBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFileChooser outputJsonFileChooser;
    private javax.swing.JFileChooser outputTextFileChooser;
    private javax.swing.JTextArea resultTxt;
    private javax.swing.JButton saveJsonBtn;
    private javax.swing.JButton saveTextBtn;
    // End of variables declaration//GEN-END:variables
}
